import 'dart:async';

import 'api_client_service.dart';
import 'api_config_service.dart';

class LegalDocumentService {
  LegalDocumentService._private();
  static final LegalDocumentService instance = LegalDocumentService._private();

  /// Bundled fallbacks used when the cloud API is unreachable or misconfigured.
  /// Keep in sync with [LegalDocumentSeeder] on the web backend.
  static const List<Map<String, dynamic>> bundledDocuments = [
    {
      'id': -1,
      'document_type': 'terms',
      'version_number': '1.0',
      'content_text': '''SIGHT (LUMI) Terms & Conditions

By creating an account and using SIGHT, you agree to allow the application to collect eye-health telemetry (blink rate, viewing distance, screen time, and derived health scores) for dependent children under your guardianship for the purpose of parental monitoring and on-site clinical review via temporary access tokens.

You acknowledge that temporary clinician access is granted only through parent-generated codes that expire after fifteen (15) minutes, and that you may end any active viewing session at any time from the mobile application.

You agree not to misuse the platform, attempt to bypass role-based access controls, or share another user's credentials.''',
      'published_at': null,
      'source': 'bundled',
    },
    {
      'id': -2,
      'document_type': 'privacy',
      'version_number': '1.0',
      'content_text': '''SIGHT (LUMI) Privacy Policy

We collect account identity data, child profile data, device calibration settings, and eye-health metrics required to operate the service. Metrics are stored in our cloud database and may be cached offline on the guardian/child device.

Clinicians may view a child's telemetry only after redeeming a short-lived OTP/QR token generated by a guardian. Each viewing event is recorded in an immutable access log visible to guardians.

We do not sell personal data. Access logs and configuration change audits are retained to support transparency and academic project compliance.''',
      'published_at': null,
      'source': 'bundled',
    },
  ];

  Future<List<Map<String, dynamic>>> fetchLatest() async {
    if (!ApiConfigService.isConfigured) {
      return List<Map<String, dynamic>>.from(bundledDocuments);
    }

    try {
      final uri = ApiConfigService.buildUri('/api/mobile/legal-documents/latest');
      final response = await ApiClientService.instance.get(uri);
      final docs = _parseDocuments(response.data);
      if (response.isSuccess && docs.isNotEmpty) {
        return docs;
      }
    } on TimeoutException {
      // fall through to bundled
    } catch (_) {
      // fall through to bundled
    }

    return List<Map<String, dynamic>>.from(bundledDocuments);
  }

  List<Map<String, dynamic>> _parseDocuments(dynamic payload) {
    if (payload is! Map) return const [];

    // Envelope: { status, message, data: { documents: [...] } }
    dynamic data = payload['data'];
    if (data is Map && data['documents'] is List) {
      return _mapList(data['documents'] as List);
    }

    // Alternate shapes: { documents: [...] } or data as a bare list
    if (payload['documents'] is List) {
      return _mapList(payload['documents'] as List);
    }
    if (data is List) {
      return _mapList(data);
    }

    return const [];
  }

  List<Map<String, dynamic>> _mapList(List raw) {
    return raw
        .whereType<Map>()
        .map((e) => Map<String, dynamic>.from(e))
        .where((e) => (e['content_text']?.toString().trim().isNotEmpty ?? false))
        .toList();
  }

  Future<bool> acceptDocuments(List<int> documentIds) async {
    // Bundled negative IDs are not persisted server-side until cloud docs are available.
    final serverIds = documentIds.where((id) => id > 0).toList();
    if (serverIds.isEmpty) return true;
    if (!ApiConfigService.isConfigured) return true;

    try {
      final uri = ApiConfigService.buildUri('/api/mobile/legal-agreements');
      final response = await ApiClientService.instance.post(uri, jsonBody: {
        'document_ids': serverIds,
      });
      return response.isSuccess;
    } catch (_) {
      return false;
    }
  }
}
